### ISSUE TITLE
Development warnings about unsupported style property

### ISSUE THREAD

**Issue by davi-mbatista** [signavio/react-stick#25]
### Description
I'm getting console warnings when using version `3.0.2`:

```
index.js:1 Warning: Unsupported style property &align-top. Did you mean &alignTop?
```

![Screen Shot 2020-03-24 at 3 05 16 PM](https://user-images.githubusercontent.com/13774283/77434271-e462bf00-6de0-11ea-8291-31a36230ae4b.png)

**Comment by frontendphil** [comment]
That sounds like you're missing a `substyle` provider. This one usually takes care of all of this.

**Comment by tzimmermann** [comment]
Also seeing this since updating on `3.0.2`.

We are (and always have been) using a style provider (`substyle-jss`), so something must have change in the new `react-stick` version.

**Comment by tzimmermann** [comment]
This is actually worse than just some warnings in the console. Important styles for positioning/alignment are not applied because of this.

It is an upgrade blocker for us currently (for `react-stick@3` and in turn also for `@signavio/ui` >=13.0.2).

You can also see the error message popping up in the test suite: https://app.circleci.com/pipelines/github/signavio/react-stick/174/workflows/10d56af7-d31e-4816-9984-852607c3d7eb/jobs/1442
while there were no such warning on v2.3.0 branch (tested locally).

@frontendphil Any ideas?

**Comment by frontendphil** [comment]
@tzimmermann this sounds weird. We should be seeing errors in other places as well if that were the case. However, we've also been using the style enhancer in our tests as well for quite some time: https://github.com/signavio/workflow-client/blob/master/jest/setupTests.js#L44

**Comment by tzimmermann** [comment]
Hm wild idea: Could it be an issue that we are using `substyle@6` and `substyle@7` in the same app? It seems as if one of the big changes between these two was using the new Context API...
So I'm thinking this might mess up stuff big time.

For some reason, [`@signavio/ui` is still on `substyle@6`](https://github.com/signavio/glucose/blob/2a5c8c10033dfd4ca1e769f738e8b9730635ec86/packages/ui/package.json#L58
).

I am gonna investigate on this...

**Comment by jfschwarz** [comment]
> For some reason, @signavio/ui is still on substyle@6 while react-stick is using substyle@7 since the recent major release.

yes, this does not work.

**Comment by tzimmermann** [comment]
> > For some reason, @signavio/ui is still on substyle@6 while react-stick is using substyle@7 since the recent major release.
> 
> yes, this does not work.

Then `@signavio/ui` should have never updated to `react-stick@3` in the first place (without also updating substyle)? 😞

**Comment by tzimmermann** [comment]
So what's the action plan here?
I would vote for reverting the react-stick upgrade in signavio/ui, as I assume upgrading to v7 (or even to the more recent versions) is no easy feat, what do you think?

Also, I am curious why you don't notice this issue in workflow-client...

**Comment by yakunins** [comment]
Greetings. I just replaced `&align-left` with `&alignLeft` and got no warnings since then.

https://github.com/signavio/react-stick/blob/aa84207d642ee7536d6fa00fbb7b6083c21b45ee/src/StickNode.js#L65

This warning is really annoying.

**Comment by yakunins** [comment]
@frontendphil May I create a fork and you grab bugfixed version out of there?

**Comment by frontendphil** [comment]
Hey @yakunins! Thanks, but the reason this didn't work correctly was a different one that had to do with the generic styling solution we're using. However, we've just upgraded it. With the new v4 you shouldn't see this behavior anymore.

**Comment by frontendphil** [comment]
@davi-mbatista @tzimmermann I'm going to close this issue. Neither the current dev build nor the prod build shows the warnings anymore.
