### ISSUE TITLE
Node position not updated correctly during scroll [v3 regression]

### ISSUE THREAD

**Issue by tzimmermann** [signavio/react-stick#56]
Since updating from `2.3.0` to `3.0.6`, in a certain scenario (re-built in codesandbox link below), I observed the following bug:

A sticky node is not moving correctly with its anchor when scrolling horizontally.
Instead, it always stays in the same (initial) position.

I built a minimal repro example here: https://codesandbox.io/s/adoring-star-lqpti

If I'd have to guess, I think that the `calculateWidth` function here is not doing what it should, but I am not able to fix the issue myself:
 https://github.com/signavio/react-stick/blob/689d09b89dabaf0a2be858a40a40a209370213ee/src/Stick.js#L230

**Comment by frontendphil** [comment]
What is it exactly that is wrong? I've recorded a gif and to me, it seems like this behaves like I would have expected. Am I getting this wrong? 

![May-05-2020 18-09-37](https://user-images.githubusercontent.com/187786/81088718-a686a980-8efb-11ea-8cc3-cd013d3217b1.gif)

**Comment by tzimmermann** [comment]
This is how it looks like for me (Chrome on Mac, Version 81.0.4044.129 (Official Build) (64-bit))
The second line does not move but stays in place while scrolling:

![react-stick](https://user-images.githubusercontent.com/1227637/81144457-631c5180-8f74-11ea-8e5c-ec31a81390be.gif)

Weird that it works for you...

**Comment by frontendphil** [comment]
I didn't notice there was another scroll-container. I've added a border so that I don't overlook this again https://codesandbox.io/s/summer-sun-0ykm

Now I can also reproduce this. Thinking about it now. If you need a temp workaround: set the `inline` prop on the `Stick` then it works as expected.

**Comment by tzimmermann** [comment]
> I didn't notice there was another scroll-container. I've added a border so that I don't overlook this again https://codesandbox.io/s/summer-sun-0ykm

Ah, also didn't notice that there was another scroll thing on the root element, sorry about that.
BTW your sandbox link gives me a 404 😬 

> set the inline prop on the Stick then it works as expected.

Thanks I will check if this works for us.
